# Generated by Django 3.2.6 on 2021-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticias_index', models.PositiveSmallIntegerField(default=5, unique=True)),
            ],
        ),
    ]
