# Generated by Django 3.2.6 on 2021-08-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_alter_configuracoes_noticias_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracoes',
            name='noticias_index',
            field=models.PositiveSmallIntegerField(default=5, unique=True),
        ),
    ]
