# Generated by Django 3.2.6 on 2021-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('texto', models.TextField()),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('edicao', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('comunicados', 'Comunicados'), ('equipamentos', 'Equipamentos'), ('compras', 'Compras'), ('manutencao', 'Manutenção'), ('treinamentos', 'Treinamentos'), ('pesquisa', 'Pesquisa')], default='comunicados', max_length=15)),
            ],
        ),
    ]
