# Generated by Django 3.2.6 on 2021-08-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('comunicados', 'Comunicados'), ('equipamentos', 'Equipamentos'), ('compras', 'Compras'), ('manutencao', 'Manutenção'), ('treinamentos', 'Treinamentos'), ('pesquisa', 'Pesquisa')], default='comunicados', max_length=15),
        ),
    ]
