# Generated by Django 3.2.6 on 2021-08-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('departamento', models.CharField(max_length=255)),
                ('conselheiro', models.BooleanField(default=False)),
            ],
        ),
    ]
