# Generated by Django 3.2.6 on 2021-08-24 19:29

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_de_perfil',
            field=models.ImageField(default='', upload_to=usuarios.models.nomear_pasta),
            preserve_default=False,
        ),
    ]
