# Generated by Django 3.2.6 on 2021-08-24 20:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_foto_de_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
