# Generated by Django 3.2.6 on 2021-08-24 23:29

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, default='../static/assets/img/fotos-perfil/Perfil_Desconhecido.jpg', upload_to=usuarios.models.nomear_pasta),
        ),
    ]
