# Generated by Django 3.2.6 on 2021-08-31 20:22

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='conselheiro',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='departamento',
        ),
        migrations.AddField(
            model_name='docente',
            name='instituicional',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='docente',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='O ramal de estar no formato de : 0000', regex='[0-9]{4}')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone de estar no formato de : (xx) xxxxx-xxxx', regex='\\([0-9]{2}\\) [0-9]{4,5}-[0-9]{4}')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_chefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_conselheiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_discente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_sub_chefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_tecnico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='operacao',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
