# Generated by Django 3.2.6 on 2021-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210831_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='operacao',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
