# Generated by Django 3.2.6 on 2021-09-01 00:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('e9d2affd-83fd-44c0-b247-a8005209e0e3'), editable=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=uuid.UUID('5c2d2b81-dfec-4962-ae43-2daa67498979'), max_length=40, unique=True),
        ),
    ]
