# Generated by Django 3.2.6 on 2021-09-01 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20210831_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('12256236-6fe7-4574-9c8e-dd702ca70c84'), editable=False),
        ),
    ]
