# Generated by Django 3.2.6 on 2021-09-09 01:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20210908_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='periodo_de_permanencia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='discente',
            name='setor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('e46aafd2-7e96-4142-bc3f-66ff8d2ab9d5'), editable=False),
        ),
    ]
