# Generated by Django 3.2.6 on 2021-09-09 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20210908_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discente',
            name='departamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('d5327a50-37ba-4b29-98ae-135bf538dd70'), editable=False),
        ),
    ]
