# Generated by Django 3.2.6 on 2021-09-13 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20210909_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo_de_instituicao', models.CharField(max_length=40)),
                ('razao_social', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='O ramal deve estar no seguinte formato: 00.000.000/0000-00', regex='/^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$/')])),
                ('cep', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='O ramal deve estar no seguinte formato: 00000-000', regex='[0-9]{5}-[0-9]{3}')])),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=250)),
                ('numero', models.IntegerField(max_length=10)),
                ('complemento', models.CharField(max_length=250)),
                ('telefone_instituicao', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone de estar no formato de : (xx) xxxxx-xxxx', regex='\\([0-9]{2}\\) [0-9]{4,5}-[0-9]{4}')])),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_externo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='O ramal deve estar no seguinte formato: 0000', regex='[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('414fa99c-a621-468a-bf10-1e68fa03a4ff'), editable=False),
        ),
    ]
