# Generated by Django 3.2.6 on 2021-09-13 19:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_auto_20210913_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externo',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('6672fac2-73b5-4c88-92e8-50cf85c5c746'), editable=False),
        ),
    ]
