# Generated by Django 3.2.6 on 2021-09-15 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20210913_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='caminho_armazenamento',
            field=models.UUIDField(default=uuid.UUID('8801fdee-d575-45e8-b912-85e236eb34f2'), editable=False),
        ),
    ]
