# Generated by Django 3.2.6 on 2021-08-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(default='Uma descrição'),
            preserve_default=False,
        ),
    ]
