# Generated by Django 3.2.6 on 2021-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='foto_de_perfil',
            field=models.ImageField(blank=True, upload_to='galeria/<django.db.models.fields.CharField>'),
        ),
    ]
