# Generated by Django 3.2.6 on 2021-08-23 19:06

from django.db import migrations, models
import equipamentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_equipamento_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='foto_de_perfil',
            field=models.ImageField(upload_to=equipamentos.models.nomear_pasta),
        ),
    ]
