# Generated by Django 3.2.6 on 2021-08-23 19:42

from django.db import migrations, models
import django.db.models.deletion
import equipamentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_alter_equipamento_foto_de_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='foto_de_perfil',
        ),
        migrations.CreateModel(
            name='GeleriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=equipamentos.models.nomear_pasta)),
                ('descricao_da_imagem', models.CharField(max_length=500)),
                ('foto_de_perfil', models.BooleanField(default=False)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='equipamentos.equipamento')),
            ],
        ),
    ]
