# Generated by Django 3.2.6 on 2021-08-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_auto_20210823_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geleriaequipamento',
            name='foto_de_perfil',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
