# Generated by Django 3.2.6 on 2021-08-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_geleriaequipamento_foto_de_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geleriaequipamento',
            name='foto_de_perfil',
            field=models.BooleanField(default=False),
        ),
    ]
