# Generated by Django 3.2.6 on 2021-08-23 22:13

from django.db import migrations, models
import equipamentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_alter_geleriaequipamento_foto_de_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='geleriaequipamento',
            name='miniatura',
            field=models.ImageField(default='', editable=False, upload_to=equipamentos.models.nomear_pasta),
            preserve_default=False,
        ),
    ]
